### ISSUE TITLE
NPM Start Failing

### ISSUE THREAD

**Issue by dchadha** [gehrj/emailProject#1]
I was able to install without any issues but when I try to start the app, I am getting the following. What is missing?

SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432
    at connection.connect.err (/mnt/c/Code/Justin/emailProject-master/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:95:24)
    at Connection.connectingErrorHandler (/mnt/c/Code/Justin/emailProject-master/node_modules/pg/lib/client.js:126:14)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/mnt/c/Code/Justin/emailProject-master/node_modules/pg/lib/connection.js:71:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1284:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'SequelizeConnectionRefusedError',
  parent:
   { Error: connect ECONNREFUSED 127.0.0.1:5432
       at Object.exports._errnoException (util.js:1034:11)
       at exports._exceptionWithHostPort (util.js:1057:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1096:14)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 5432 },
  original:
   { Error: connect ECONNREFUSED 127.0.0.1:5432
       at Object.exports._errnoException (util.js:1034:11)
       at exports._exceptionWithHostPort (util.js:1057:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1096:14)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 5432 } }

**Comment by dchadha** [comment]
@gehrj Please update the issue once you have made the change so I know when to download the latest packages. 

Thanks!

**Comment by gehrj** [comment]
@dchadha So I had my friend run it on their computer and it worked fine, they also had to run the command "createdb AutoMech" in command line to create database on their local machine. I'm thinking you are missing something related to the way I set up the backend. I feel like you said you did, but do you have postgreSQL installed? Also you may need to setup your $path this link should help with that http://postgresapp.com/documentation/cli-tools.html

**Comment by gehrj** [comment]
Confirmed that the issue is with PostgreSQL not running on machine. Starting PostgreSQL should resolve issue.
